name: Commit Check

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  commit-check:
    runs-on: ubuntu-24.04
    permissions: # use permissions because use of pr-comments
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0  # Required for merge-base checks
      - uses: commit-check/commit-check-action@v2
        env:
          CCHK_IGNORE_AUTHORS: "dependabot[bot]"
        with:
          message: true
          branch: false
          author-name: false
          author-email: false
          job-summary: true
          pr-comments: true
          pr-title: true
